Fix Docker build failure
requirements.txt depends on base_requirements.txt

STEP 6: RUN pip install -r requirements.txt
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'base_requirements.txt'